"""Initial migration

Revision ID: 1e2ae156c9fe
Revises: 
Create Date: 2024-10-12 21:59:48.018926

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '1e2ae156c9fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
