"""row info store

Revision ID: 2077d9c06b81
Revises: 39626cdc6b1e
Create Date: 2024-10-13 12:39:37.709134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2077d9c06b81'
down_revision: Union[str, None] = '39626cdc6b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_external_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['oauth_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_external_data_id'), 'raw_external_data', ['id'], unique=False)
    op.create_index('ix_raw_external_data_provider_user', 'raw_external_data', ['provider_id', 'provider_user_id'], unique=False)
    op.create_index(op.f('ix_raw_external_data_user_id'), 'raw_external_data', ['user_id'], unique=False)
    op.add_column('oauth_accounts', sa.Column('token_id', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('oauth_accounts', 'token_id')
    op.drop_index(op.f('ix_raw_external_data_user_id'), table_name='raw_external_data')
    op.drop_index('ix_raw_external_data_provider_user', table_name='raw_external_data')
    op.drop_index(op.f('ix_raw_external_data_id'), table_name='raw_external_data')
    op.drop_table('raw_external_data')
    # ### end Alembic commands ###
