"""add user model

Revision ID: 39626cdc6b1e
Revises: 3bd441448300
Create Date: 2024-10-13 11:54:46.133268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39626cdc6b1e'
down_revision: Union[str, None] = '3bd441448300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('oauth_accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index('ix_oauth_accounts_provider_user', 'oauth_accounts', ['provider_id', 'provider_user_id'], unique=False)
    op.create_foreign_key(None, 'oauth_accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_accounts', type_='foreignkey')
    op.drop_index('ix_oauth_accounts_provider_user', table_name='oauth_accounts')
    op.drop_column('oauth_accounts', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
