"""add auth

Revision ID: 3bd441448300
Revises: 1e2ae156c9fe
Create Date: 2024-10-12 22:35:27.770626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd441448300'
down_revision: Union[str, None] = '1e2ae156c9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

oauth_providers = sa.table(
    'oauth_providers',
    sa.column('id', sa.Integer),
    sa.column('name', sa.String),
    sa.column('client_id', sa.String),
    sa.column('client_secret', sa.String),
    sa.column('redirect_uri', sa.String),
    sa.column('created_at', sa.DateTime(timezone=True)),
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_oauth_providers_id'), 'oauth_providers', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_providers_name'), 'oauth_providers', ['name'], unique=True)


    op.bulk_insert(
        oauth_providers,
        [
            {
                "id": 1,
                "name": "vk.com",
                "client_id": "52467648",
                "client_secret": "",  # TODO fill manually
                "redirect_uri": "https://iktomi.pro/vk-login",
            }
        ]
    )

    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['oauth_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_oauth_accounts_id'), 'oauth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_provider_user_id'), 'oauth_accounts', ['provider_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_accounts_provider_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_oauth_providers_name'), table_name='oauth_providers')
    op.drop_index(op.f('ix_oauth_providers_id'), table_name='oauth_providers')
    op.drop_table('oauth_providers')
    # ### end Alembic commands ###
