name: Deploy to Server

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy Files to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "rm -rf ~/github-deploy || true"
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p ~/github-deploy"
        scp -o StrictHostKeyChecking=no -r * ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/github-deploy

    - name: Create .env file
      run: |
        touch .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}\n" >> .env
        echo "RPC_URL=${{ secrets.RPC_URL }}" >> .env
        scp -o StrictHostKeyChecking=no  .env ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/github-deploy/scr/back/.env

    - name: Deploy Front Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ~/github-deploy
          docker compose build iktomi-front iktomi-back
          docker compose up -d iktomi-front
        EOF